name: Hockey Parser

on:
  push:
    branches: [ main ]
  workflow_dispatch: # ЭТА СТРОКА ВАЖНА — она добавляет кнопку "Run workflow"

jobs:
  run-parser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium
          
      - name: Run script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python Sportac.py
