name: Run Hockey Parser

on:
  schedule:
    # 17:00-23:00 МСК = 14:00-20:00 UTC
    - cron: '0 14,15,16,17,18,19,20 * * *'
    # 00:00-07:00 МСК = 21:00 UTC (пн-сб) и 22:00-04:00 UTC
    - cron: '0 21,22,23,0,1,2,3,4 * * *'
  workflow_dispatch:

jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests

      - name: Install Playwright Browsers
        run: |
          python -m playwright install chromium --with-deps

      - name: Run parser script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python Sportac.py
